// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file ddsDemoSubscriber.h
 * This header file contains the declaration of the subscriber functions.
 *
 * This file was generated by the tool fastcdrgen.
 */


#ifndef _DDSDEMO_SUBSCRIBER_H_
#define _DDSDEMO_SUBSCRIBER_H_

#include <fastrtps/fastrtps_fwd.h>
#include <fastrtps/subscriber/SubscriberListener.h>
#include <fastrtps/subscriber/SampleInfo.h>
#include "ddsDemoPubSubTypes.h"

using namespace eprosima::fastrtps;

class ddsDemoSubscriber 
{
public:
	ddsDemoSubscriber();
	virtual ~ddsDemoSubscriber();
	bool init();
	void run();
private:
	Participant *mp_participant;
	Subscriber *CP_reader;
	Subscriber *LPBC_reader;
	Subscriber *TL_reader;
	Subscriber *H_reader;
	Subscriber *T_reader;
	Subscriber *L_reader;
	Subscriber *S_reader;
	Subscriber *GL_reader;
	Subscriber *PT_reader;
	
	class SubListener : public SubscriberListener
	{
	public:
		SubListener() : n_matched(0),n_msg(0){};
		~SubListener(){};
		void onSubscriptionMatched(Subscriber* sub,MatchingInfo& info);
		void onNewDataMessage(Subscriber* sub);
		SampleInfo_t m_info;
		int n_matched;
		int n_msg;
	} m_listener;
	
	CarparkPubSubType CP_type;
	LamppostsBCPubSubType LPBC_type;
	TrafficlightPubSubType TL_type;
	HumidityPubSubType H_type;
	TemperaturePubSubType T_type;
	LightPubSubType L_type;
	SpeedingPubSubType S_type;
	GeoLocationPubSubType GL_type;
	PriorityPubSubType PT_type;
};

#endif // _ddsDemo_SUBSCRIBER_H_